language: ruby
rvm:
  - 2.6.0
  - jruby
  - truffleruby
  - 2.6.0p0
before_script:
  - gem update --system
  - gem install bundler
  - rm fr public
script:
  - bundle exec jekyll build

branches:
  only:
    - master
