language: ruby
rvm:
  - 2.6.0
  - jruby
  - truffleruby

before_script:
  - gem update --system
  - gem install bundler
  - rm rf public
script:
  - bundle exec jekyll build

branches:
  only:
    - master
