# Website settings
url: "https://www.douglaschifetete.co.za"
title: Douglas S. Chifetete
# Internal nav
nav:
  main:
    writing: "/writing"
    projects: "/projects"
    photos: "https://www.instagram.com/doug_shingi"

  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Douglas Shingirayi Chifetete"
description: "The home page of Douglas (Shingi) Chifetete, blogger and software engineer at Entelect."
thumbnail_path: "profile-photos/douglas-chifetete.png"
website_repo_url: "https://github.com/douglaschifetete/douglaschifetete.github.io"
entelect_url: "https://www.entelect.co.za"
destination: public
future: true
# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/dschifetete"
    label: "Twitter"
    icon: "twitter-square"
    username: "@dschifetete"
  linkedin:
    url: "https://www.linkedin.com/in/douglas-chifetete/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/mufukuri/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:douglas.chifetete@gmail.com"
    label: "Email"
    value: "douglas.chifetete@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Africa/Harare'
repository: douglaschifetete/douglaschifetete.github.io

disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: my_disqus_shortname
# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
